/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedPortfolioRouteImport } from './routes/_authed/portfolio'
import { Route as AuthedOptimizarRouteImport } from './routes/_authed/optimizar'
import { Route as AuthedBacktestRouteImport } from './routes/_authed/backtest'
import { Route as AuthedActividadRouteImport } from './routes/_authed/actividad'
import { Route as AuthedCoinSymbolRouteImport } from './routes/_authed/coin/$symbol'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPortfolioRoute = AuthedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOptimizarRoute = AuthedOptimizarRouteImport.update({
  id: '/optimizar',
  path: '/optimizar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBacktestRoute = AuthedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActividadRoute = AuthedActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCoinSymbolRoute = AuthedCoinSymbolRouteImport.update({
  id: '/coin/$symbol',
  path: '/coin/$symbol',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth': typeof AuthRoute
  '/actividad': typeof AuthedActividadRoute
  '/backtest': typeof AuthedBacktestRoute
  '/optimizar': typeof AuthedOptimizarRoute
  '/portfolio': typeof AuthedPortfolioRoute
  '/coin/$symbol': typeof AuthedCoinSymbolRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/actividad': typeof AuthedActividadRoute
  '/backtest': typeof AuthedBacktestRoute
  '/optimizar': typeof AuthedOptimizarRoute
  '/portfolio': typeof AuthedPortfolioRoute
  '/': typeof AuthedIndexRoute
  '/coin/$symbol': typeof AuthedCoinSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/actividad': typeof AuthedActividadRoute
  '/_authed/backtest': typeof AuthedBacktestRoute
  '/_authed/optimizar': typeof AuthedOptimizarRoute
  '/_authed/portfolio': typeof AuthedPortfolioRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/coin/$symbol': typeof AuthedCoinSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/actividad'
    | '/backtest'
    | '/optimizar'
    | '/portfolio'
    | '/coin/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/actividad'
    | '/backtest'
    | '/optimizar'
    | '/portfolio'
    | '/'
    | '/coin/$symbol'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/actividad'
    | '/_authed/backtest'
    | '/_authed/optimizar'
    | '/_authed/portfolio'
    | '/_authed/'
    | '/_authed/coin/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/portfolio': {
      id: '/_authed/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthedPortfolioRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/optimizar': {
      id: '/_authed/optimizar'
      path: '/optimizar'
      fullPath: '/optimizar'
      preLoaderRoute: typeof AuthedOptimizarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backtest': {
      id: '/_authed/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthedBacktestRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/actividad': {
      id: '/_authed/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof AuthedActividadRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coin/$symbol': {
      id: '/_authed/coin/$symbol'
      path: '/coin/$symbol'
      fullPath: '/coin/$symbol'
      preLoaderRoute: typeof AuthedCoinSymbolRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActividadRoute: typeof AuthedActividadRoute
  AuthedBacktestRoute: typeof AuthedBacktestRoute
  AuthedOptimizarRoute: typeof AuthedOptimizarRoute
  AuthedPortfolioRoute: typeof AuthedPortfolioRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCoinSymbolRoute: typeof AuthedCoinSymbolRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActividadRoute: AuthedActividadRoute,
  AuthedBacktestRoute: AuthedBacktestRoute,
  AuthedOptimizarRoute: AuthedOptimizarRoute,
  AuthedPortfolioRoute: AuthedPortfolioRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCoinSymbolRoute: AuthedCoinSymbolRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
